node:
  name: head#1
  ip: 0.0.0.0
  port: 9527
  key_path: /Users/derekanderson/Projects/blockless/net2/configs/testkeys/priv.bin
  use_static_keys: true
  workspace_root: /tmp/head
  runtime_path: /tmp/runtime
rest:
  ip: 0.0.0.0
  port: 8081
protocol:
  role: head
logging:
  file_path: stdout
  level: info
repository:
  url: http://localhost:8080/
chain:
  address_key: "alice"
  rpc: "http://0.0.0.0:26657"
